### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/CK2JPModAppendixI#13]
![image](https://user-images.githubusercontent.com/35730970/55744113-0f88bd00-5a6f-11e9-8a96-886e22ac1fc3.png)

**Comment by matanki-saito** [comment]
イベントはこれ。
https://paratranz.cn/projects/91/strings?id=11089918
英語版だとちゃんと出る。
![image](https://user-images.githubusercontent.com/35730970/56091061-fb1c4880-5ee4-11e9-82b3-97c8976cce07.png)

イベントの出し方は```event WoL.530```

**Comment by matanki-saito** [comment]
問題のテキストはこれっぽい
https://paratranz.cn/projects/91/strings?id=6764680

**Comment by matanki-saito** [comment]
これは$TYPE$のところに別のテキストが入ってしまっている。本来は「侍女」にならないといけない。

**Comment by matanki-saito** [comment]
$TYPE$を消す。
![image](https://user-images.githubusercontent.com/35730970/56091388-47698780-5ee9-11e9-8845-7b1fb7e5055a.png)

**Comment by matanki-saito** [comment]
本来埋め込まれるはずのwomenは２つしかない
![image](https://user-images.githubusercontent.com/35730970/56091400-767ff900-5ee9-11e9-892f-d8678be17632.png)

**Comment by matanki-saito** [comment]
元テキストだと、
```
NAMED_CHARACTER_CREATED;$TYPE$ named §Y$NAME$§! appears at the court of ~
```
でCHAR_COURTIER_FEMALEが埋め込まれてるのか？

**Comment by matanki-saito** [comment]
なるほど、CHAR_COURTIER_FEMALEは本来、
```
CHAR_COURTIER_FEMALE;A woman;
```
だが、Paratranz上では正しくオリジナルのテキストが表示されていないな。
https://paratranz.cn/projects/91/strings?id=11089917

**Comment by matanki-saito** [comment]
わかった…キーが重複してるな。LT.csvの1112行目にあり、

![image](https://user-images.githubusercontent.com/35730970/56092243-76d1c180-5ef4-11e9-929a-55e0aa275854.png)

1354行目にもある。
![image](https://user-images.githubusercontent.com/35730970/56092249-80f3c000-5ef4-11e9-9b0b-5ca08feb9f47.png)

**Comment by matanki-saito** [comment]
どうもCK2は重複したキーがある場合は最初のものしか採用しないようだ。しかしparatranzにインポートした時点で、重複キーは後ろにでてきたものが採用される。

そもそも重複キーが存在することがおかしいのでもとのゲームのバグと言える。

**Comment by kosaki** [comment]
あ、これちょうどハマっていたやつです。
ありがとうございます。ありがとうございます。
